KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employees__c/Antra_Employees__c.object-meta.xml
<CustomObject>
    <label>Antra Employees</label>
    <nameField>
        <displayFormat>AEMP{000}</displayFormat>
        <label>Antra Employees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Antra Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employees__c/fields/Employee_Salary__c.field-meta.xml
<CustomField>
    <fullName>Employee_Salary__c</fullName>
    <label>Employee Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employees__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Not Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/classes/AntraAssement2test.cls
@istest
public class AntraAssement2test {
@istest
    public static void method1(){
        Antra_Employees__c em=new Antra_Employees__c();
        em.Employee_Salary__c=26000;
        em.Status__c='Not Selected';
        insert em;
        Antra_Employees__c em1=new Antra_Employees__c();
        em1.Employee_Salary__c=20000;
        em1.Status__c='Selected';
        insert em1;
        AntraAssesmentq2 asse=new AntraAssesmentq2();
        database.executeBatch(asse);
    }
}