KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employees__c/Antra_Employees__c.object-meta.xml
<CustomObject>
    <label>Antra Employees</label>
    <nameField>
        <displayFormat>AEMP{000}</displayFormat>
        <label>Antra Employees ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Antra Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employees__c/fields/Employee_Salary__c.field-meta.xml
<CustomField>
    <fullName>Employee_Salary__c</fullName>
    <label>Employee Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employees__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Not Selected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/classes/AntraAssesmentq2.cls
public class AntraAssesmentq2 implements database.Batchable<sobject>
{
    public database.QueryLocator start(database.BatchableContext bc){
        string query='select id,Name,Status__c,Employee_Salary__c  from Antra_Employees__c ';
        return database.getQueryLocator(query);
    }
    public void execute(database.BatchableContext bc,list<Antra_Employees__c>emp){
        list<Antra_Employees__c> selectlist=new list<Antra_Employees__c>();
       // list<Antra_Employees__c> unselectlist=new list<Antra_Employees__c>();
        for(Antra_Employees__c em:emp){
            if(em.Employee_Salary__c>25000){
                delete em;
            }else{
                em.Status__c='Not Selected';
                selectlist.add(em);
            }
            update selectlist;
        }
    }
    public void finish(database.BatchableContext bc){
        
    }
}