KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/Employee_Details__c.object-meta.xml
<CustomObject>
    <label>Employee Details</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <displayFormat>DEL-{0000}</displayFormat>
    <label>Employee ID</label>
    <type>AutoNumber</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Employee_name__c.field-meta.xml
<CustomField>
    <fullName>Employee_name__c</fullName>
    <formula>text(Salution__c) + Last_name__c +&apos;  &apos;+ Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee name</label>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/AntraDmlprac.cls
public class AntraDmlprac {
    public string input{get;set;}
    public string Mobile{get;set;}
    public Employee_Details__c emp;
    public string opmsg{get;set;}
    public string opname{get;set;}
    
    public void search(){
        integer cut=[select count() from Employee_Details__c where Employee_ID__c = : input];
        if(cut>=1){
            emp=[select Phone_number__c,Employee_name__c from Employee_Details__c where Employee_ID__c = : input limit 1];
            mobile=emp.Phone_number__c;
            opname=emp.Employee_name__c;
        }else{
            opmsg='sorry macha unable to find the record';
        }
    }
    
    public void updatevalue(){
        emp.Phone_number__c=mobile;
        update emp;
    }

}