KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/Employee_Details__c.object-meta.xml
<CustomObject>
    <label>Employee Details</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>(today()-Date_of_Birth__c)/365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/antramay19hand.cls
public class antramay19hand {
    public string ename{get;set;}
    public decimal age{get;set;}
    public string email{get;set;}
    list<Employee_Details__c>empd;
    public list<Employee_Details__c> emptyli{get;set;}
   public antramay19hand(){
        empd=[select Name, Age__c, Email_ID__c from Employee_Details__c];
    }
    public void search(){
        emptyli=new list<Employee_Details__c>();
        if(ename!=''){
            for(Employee_Details__c e1:empd){
                if(e1.Name==ename){
                    emptyli.add(e1);
                }
            }
        }
        else if(age>0){
            for(Employee_Details__c e1:empd){
                if(e1.Age__c > age){
                    emptyli.add(e1);
                }
            }
        }
         else if(email!=''){
            for(Employee_Details__c e1:empd){
                if(e1.Email_ID__c==email){
                    emptyli.add(e1);
                }
            }
        }
    }
}