KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/Employee_Details__c.object-meta.xml
<CustomObject>
    <label>Employee Details</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>(today()-Date_of_Birth__c)/365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Bank_name__c.field-meta.xml
<CustomField>
    <fullName>Bank_name__c</fullName>
    <label>Bank name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/date_of_joining__c.field-meta.xml
<CustomField>
    <fullName>date_of_joining__c</fullName>
    <label>date of joining</label>
    <type>Date</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Employe_status__c.field-meta.xml
<CustomField>
    <fullName>Employe_status__c</fullName>
    <label>Employe status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE,</fullName>
            </value>
            <value>
                <fullName>LONG LEAVE</fullName>
            </value>
            <value>
                <fullName>MATERNITY LEAVE</fullName>
            </value>
            <value>
                <fullName>PROBATION</fullName>
            </value>
            <value>
                <fullName>RELIEVED</fullName>
            </value>
            <value>
                <fullName>RESIGNED</fullName>
            </value>
            <value>
                <fullName>SABBATICAL</fullName>
            </value>
            <value>
                <fullName>SUSPENDED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Employee_Active_status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Active_status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Employee Active status</label>
    <type>Checkbox</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Employee_name__c.field-meta.xml
<CustomField>
    <fullName>Employee_name__c</fullName>
    <formula>text(Salution__c) + Last_name__c +&apos;  &apos;+ Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee name</label>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Monthly_salary__c.field-meta.xml
<CustomField>
    <fullName>Monthly_salary__c</fullName>
    <label>Monthly salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/PAN_Number__c.field-meta.xml
<CustomField>
    <fullName>PAN_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>PAN Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Salary_Record__c/Salary_Record__c.object-meta.xml
<CustomObject>
    <label>Salary Records</label>
    <nameField>
        <displayFormat>dsal/{mm}/{yy}-{00}</displayFormat>
        <label>Salary Record number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salary Record</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Salary_Record__c/fields/BASIC_SALARY__c.field-meta.xml
<CustomField>
    <fullName>BASIC_SALARY__c</fullName>
    <label>BASIC SALARY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Salary_Record__c/fields/EMPLOYEE_NAME__c.field-meta.xml
<CustomField>
    <fullName>EMPLOYEE_NAME__c</fullName>
    <label>Employee First Name</label>
    <referenceTo>Employee_Details__c</referenceTo>
    <relationshipLabel>Salary Record</relationshipLabel>
    <relationshipName>Salary_Record</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Salary_Record__c/fields/Monthly_Gross_Salary__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Gross_Salary__c</fullName>
    <formula>( BASIC_SALARY__c + HRA__c+ Employee_PF_contribution__c + Employer_contribution__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Gross Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Salary_Record__c/fields/Professional_Tax__c.field-meta.xml
<CustomField>
    <fullName>Professional_Tax__c</fullName>
    <label>Professional Tax</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/payslipproject.cls
public class payslipproject {
    public static boolean runonce=true;
    /*"Bank Name should only contain alphabets and must be only in capital letters
If user enters in small letters, it should be converted to capital letters"*/
    public static void req3(list<Employee_Details__c> Empd1){
        //st<Employee_Details__c> Empd1;
        for(Employee_Details__c Empd2:Empd1){
            Empd2.Bank_name__c=Empd2.Bank_name__c.touppercase(); // to uppercase
        }
    }
    /*"If Account number is entered, then IFSC Code should be made as mandatory
IFSC code should be in combination of alphanumeric and should not accept special characters and only be 11 digits"*/
    public static void req4(list<Employee_Details__c> Empd1){
        for(Employee_Details__c Empd2:Empd1){
            if(Empd2.Bank_name__c!=null && Empd2.IFSC_Code__c==null){
                Empd2.IFSC_Code__c.adderror('IFSC code shouldnt be Blank');
            }
        }
    }
    /*"PAN Number should be in combination of alphanumber and must be only 10 digits
Ex: ABCDE1234F (it should accept only this format)"*/
    public static void req5(list<Employee_Details__c> Empd1){
        //st<Employee_Details__c> Empd1;
        for(Employee_Details__c Empd2:Empd1){
            Empd2.PAN_Number__c=Empd2.PAN_Number__c.touppercase(); // to uppercase
        }
    }
    /*"AADHAAR Number should be of 12 digits and should not accept special characters, alphabets, same numbers
Ex: It should not accept numbers like 0000 0000 0000,1111 1111 1111,…...."*/
    public static void req6(list<Employee_Details__c> Empd1){
        for(Employee_Details__c Empd2:Empd1){
            if(Empd2.Aadhar_Number__c=='000000000000' ||Empd2.Aadhar_Number__c=='111111111111' || 
               Empd2.Aadhar_Number__c=='222222222222' || Empd2.Aadhar_Number__c=='333333333333' || 
               Empd2.Aadhar_Number__c=='444444444444' || Empd2.Aadhar_Number__c=='555555555555' ||
               Empd2.Aadhar_Number__c=='666666666666' || Empd2.Aadhar_Number__c=='777777777777' ||
               Empd2.Aadhar_Number__c=='888888888888' || Empd2.Aadhar_Number__c=='999999999999'){
                   Empd2.Aadhar_Number__c.adderror('Enter valid aadhar number');
               }
        }
    }
    /*"Phone Number should only be 10 digits(only numbers) and must begin with either 6 or 7 or 8 or 9
Ex: It should not accept numbers like 0000000000,1111111111,…...."*/
    public static void req8(list<Employee_Details__c> Empd1){
        for(Employee_Details__c Empd2:Empd1){
            /*if(Empd2.Phone_number__c=='0000000000' ||Empd2.Phone_number__c=='1111111111' || 
               Empd2.Phone_number__c=='2222222222' || Empd2.Phone_number__c=='3333333333' || 
               Empd2.Phone_number__c=='4444444444' || Empd2.Phone_number__c=='5555555555' ||
               Empd2.Phone_number__c=='6666666666' || Empd2.Phone_number__c=='7777777777' ||
               Empd2.Phone_number__c=='8888888888' || Empd2.Phone_number__c=='9999999999')*/
            if(Empd2.Phone_number__c.contains('999999'))
            {
                   Empd2.Phone_number__c.adderror('Enter valid phone number');
               }
        }
    }
    /*trigger for employee active status*/
    public static void req9(list<Employee_Details__c> Empd1){
        for(Employee_Details__c Empd2:Empd1){
            if(Empd2.Last_working_date__c!=null){
                Empd2.Employee_Active_status__c=false;
            }else(Empd2.Employee_Active_status__c=true);
        }
    }
    //Program for TDS
    public static void req10(list<Salary_Record__c>sal1){
        for(Salary_Record__c sal2:sal1){
            if(sal2.BASIC_SALARY__c>20000 ){
                sal2.Professional_Tax__c=200;
            }else(sal2.Professional_Tax__c=150);
        }
    }
    /*DOL should not be before DOJ, add a field for Date of resignation, Date of Leaving*/
    public static void req112(list<Employee_Details__c> Empd1){
        for(Employee_Details__c Empd2:Empd1){
            if(Empd2.Last_working_date__c<Empd2.date_of_joining__c){
                Empd2.Last_working_date__c.adderror('Last Day of working shouldnt be less than Date of Joining');
            }
        }
    }
    /*11.DOB- Age of employee should be minimum 21 years*/
    public static void req11(list<Employee_Details__c> Empd1){
        for(Employee_Details__c Empd2:Empd1){
            if(Empd2.Age__c<21){
                Empd2.Date_of_Birth__c.adderror('Employee Age should be minimum 21 years');
            }
        }
    }
    /*Only one active salary record should be present for each employee*/
    public static void req92(list<Employee_Details__c> Empd1){
        for(Employee_Details__c Empd2:Empd1){
            IF(Empd2.Last_working_date__c==null && Empd2.Employee_Active_status__c==true){
                Salary_Record__c sal1=new Salary_Record__c();
                sal1.EMPLOYEE_NAME__c=Empd2.id;
                insert sal1;
            }
        }       
    }
    /*In employee master tab cretae a list view to show all ACTIVE employees*/
     public static void req28(list<Employee_Details__c> Empd1){
        for(Employee_Details__c Empd2:Empd1){
            IF(Empd2.Employee_Active_status__c==true){
                Empd2.Employe_status__c='ACTIVE,';
        }       
    }
}
    /*In employee master tab cretae a list view to show all employee whose monthly gross more than 50000*/
    public static void req30(list<Salary_Record__c>sal1){
        set<id> sal1set=new  set<id>();
        for(Salary_Record__c sal2:sal1){
            if(sal2.EMPLOYEE_NAME__c!=null){
            sal1set.add(sal2.EMPLOYEE_NAME__c);
            }
        }
            list<Employee_Details__c> Empd1=[SELECT id,name,Monthly_salary__c from  Employee_Details__c where id in: sal1set];
            for(Employee_Details__c Empd2:Empd1){
                Empd2.Monthly_salary__c=Sal1[0].Monthly_Gross_Salary__c;
            }
            update Empd1;
    }
    /*duplicate records delete*/
    public static void masssaldel(){
      List<Salary_Record__c> Accounts = [Select ID, Name from Salary_Record__c];
set<string> DuplicateCheck = new set<string>();
set<Id> DupAccountIds = new set<Id>();
for(Salary_Record__c acc: Accounts){
	if(!DuplicateCheck.add(acc.Name))
	DupAccountIds.add(acc.Id);
}

delete [select Id from Salary_Record__c where Id IN :DupAccountIds];
    }
}