KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/Employee_Details__c.object-meta.xml
<CustomObject>
    <label>Employee Details</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Employee_name__c.field-meta.xml
<CustomField>
    <fullName>Employee_name__c</fullName>
    <formula>text(Salution__c) + Last_name__c +&apos;  &apos;+ Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee name</label>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Salary_Record__c/Salary_Record__c.object-meta.xml
<CustomObject>
    <label>Salary Records</label>
    <nameField>
        <displayFormat>dsal/{mm}/{yy}-{00}</displayFormat>
        <label>Salary Record number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salary Record</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Salary_Record__c/fields/EMPLOYEE_NAME__c.field-meta.xml
<CustomField>
    <fullName>EMPLOYEE_NAME__c</fullName>
    <label>Employee First Name</label>
    <referenceTo>Employee_Details__c</referenceTo>
    <relationshipLabel>Salary Record</relationshipLabel>
    <relationshipName>Salary_Record</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/paysliphandler.cls
public class paysliphandler {
    /*public paysliphandler(ApexPages.StandardController stdController){}
    public list<Salary_Record__c> empsal{get;set;}
    public list<Employee_Details__c> empd{get;set;}*/
    public Employee_Details__c emp{get;set;}
    public Salary_Record__c sal{get;set;}
     public String currentTab {get;set;}
    public paysliphandler(){
        emp =new Employee_Details__c();
        sal=new Salary_Record__c();
    }
    public pagereference saverecord(){
        emp.Last_name__c=emp.Last_name__c;
        insert emp;
        Employee_Details__c empd1=new Employee_Details__c();
        //empd1.Name=Employee_Details__c.Name;
        Salary_Record__c empsal1=new Salary_Record__c();
        empsal1.EMPLOYEE_NAME__c=empd1.id;
        insert empsal1;
        sal.EMPLOYEE_NAME__c=emp.Id;
        insert sal;
        pagereference p=new pagereference('/'+emp.Id);
        return p;
    }
/*public void switch()
    {
        currentTab = '1';
    } 
   // public void switch() { currentTab = String.valueOf(Integer.valueOf(currentTab)+1); }
    public void Prev() { currentTab = String.valueOf(Integer.valueOf(currentTab)-1); }*/
    public pagereference nextpage(){
       pagereference p=new pagereference('/apex/newempvfp2');
        return p; 
    }
    public pagereference previouspage(){
       //pagereference p=new pagereference('/apex/newempvfp');
        return page.newempvfp; 
    }
}