KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/Employee_Details__c.object-meta.xml
<CustomObject>
    <label>Employee Details</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Employee_name__c.field-meta.xml
<CustomField>
    <fullName>Employee_name__c</fullName>
    <formula>text(Salution__c) + Last_name__c +&apos;  &apos;+ Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee name</label>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Salution__c.field-meta.xml
<CustomField>
    <fullName>Salution__c</fullName>
    <label>Salution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Drs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Hon.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Salary_Record__c/Salary_Record__c.object-meta.xml
<CustomObject>
    <label>Salary Records</label>
    <nameField>
        <displayFormat>dsal/{mm}/{yy}-{00}</displayFormat>
        <label>Salary Record number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salary Record</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Salary_Record__c/fields/BASIC_SALARY__c.field-meta.xml
<CustomField>
    <fullName>BASIC_SALARY__c</fullName>
    <label>BASIC SALARY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Salary_Record__c/fields/EMPLOYEE_NAME__c.field-meta.xml
<CustomField>
    <fullName>EMPLOYEE_NAME__c</fullName>
    <label>Employee First Name</label>
    <referenceTo>Employee_Details__c</referenceTo>
    <relationshipLabel>Salary Record</relationshipLabel>
    <relationshipName>Salary_Record</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/newemployeevfpage.cls
public class newemployeevfpage {
    public Employee_Details__c empd{get;set;}
    public string empname{get;set;}
    public string emplastname{get;set;}
    Public string newSalution{get;set;}
    public date newDate_of_Birth{get;set;}
    public Salary_Record__c sal{get;set;}
    public integer basicsalary{get;set;}
    
    public newemployeevfpage(){
        empd =new Employee_Details__c();
        sal=new Salary_Record__c();
    }
    
    public pagereference next(){
        pagereference p=new pagereference('/apex/newempvfp2');
        return p; 
    }
    public pagereference submit(){
         empd=new Employee_Details__c();
        empd.Name=empname;
        empd.Last_name__c=emplastname;
        empd.Date_of_Birth__c=newDate_of_Birth;
        empd.Salution__c=newSalution;
        insert empd;
        sal.EMPLOYEE_NAME__c=empd.id;
        sal.BASIC_SALARY__c=basicsalary;
        insert sal;
        pagereference p=new pagereference('/'+empd.Id);
        return p; 
    }
    /* for pick list option*/
   Public List<selectOption> getSalution()
    {
        List<selectOption> saluList = new List<selectOption>();
        //saluList.add(new selectOption('other','--other--'));
        List<Schema.PicklistEntry> getsaluList = Employee_Details__c.Salution__c.getDescribe().getPickListValues();
        for(Schema.PicklistEntry saluList2 : getsaluList)
        {
            saluList.add(new selectOption(saluList2.getValue(),saluList2.getLabel()));
        }
        return saluList;
    }
    public pagereference prev(){
        pagereference p=new pagereference('/apex/newempvfp');
        return p; 
    }
}