KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/Employee_Details__c.object-meta.xml
<CustomObject>
    <label>Employee Details</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>(today()-Date_of_Birth__c)/365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/date_of_joining__c.field-meta.xml
<CustomField>
    <fullName>date_of_joining__c</fullName>
    <label>date of joining</label>
    <type>Date</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <displayFormat>DEL-{0000}</displayFormat>
    <label>Employee ID</label>
    <type>AutoNumber</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Employee_name__c.field-meta.xml
<CustomField>
    <fullName>Employee_name__c</fullName>
    <formula>text(Salution__c) + Last_name__c +&apos;  &apos;+ Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee name</label>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/antrasoql1.cls
public class antrasoql1 {
    public string emp{get;set;}
    public list<Employee_Details__c> acc{get;set;}
    public integer opval{get;set;}
    public  void submit(){
        acc=[SELECT Name, Last_name__c, Employee_name__c, Date_of_Birth__c, Age__c,
             date_of_joining__c, Employee_ID__c, Gender__c FROM Employee_Details__c where Name=:emp ];
       list<aggregateresult> agg=[select COUNT(Name)numb from Employee_Details__c where Name=:emp];
        for(aggregateresult agg1:agg){
            opval=(integer)agg1.get('numb');
        }
        
    }

}