KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <displayFormat>SUP-{000}</displayFormat>
        <label>Supplier id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Supplier__c/fields/Supplier_Address__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Address__c</fullName>
    <label>Supplier Address</label>
    <type>TextArea</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Supplier__c/fields/Supplier_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Email_ID__c</fullName>
    <label>Supplier Email ID</label>
    <type>Email</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Supplier__c/fields/Supplier_mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Supplier_mobile_Number__c</fullName>
    <label>Supplier mobile Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Supplier__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <label>Supplier Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/classes/Insert_Supplier.cls
public class Insert_Supplier 
{
    public string supplierName{get;set;}
    public string supplierMno{get;set;}
    public string supplierEmail{get;set;}
    public string supplierAddress{get;set;}
    public list<Supplier__c> supli{get;set;}
    
    public void ADD(){
        Supplier__c sup=new Supplier__c();
        sup.Supplier_Name__c=supplierName;
        sup.Supplier_mobile_Number__c=supplierMno;
        sup.Supplier_Email_ID__c=supplierEmail;
        sup.Supplier_Address__c=supplierAddress;
        insert sup;
        supli=[select Supplier_Name__c, Supplier_mobile_Number__c, Supplier_Email_ID__c, Supplier_Address__c,Name  
               from Supplier__c where Supplier_Name__c  =:supplierName ];
        
    }
}