KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <displayFormat>SUP-{000}</displayFormat>
        <label>Supplier id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Supplier__c/fields/Supplier_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Email_ID__c</fullName>
    <label>Supplier Email ID</label>
    <type>Email</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Supplier__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <label>Supplier Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/classes/AntraAssesmentmail.cls
public class AntraAssesmentmail {
    @InvocableMethod
    public static void method1(){
        EmailTemplate et = [select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where DeveloperName ='Supplier_Onboard'];
        list<Supplier__c> suplist=[select id,Name,Supplier_Email_ID__c,Supplier_Name__c from Supplier__c];
        for(Supplier__c  a:suplist){
        messaging.SingleEmailMessage email=new messaging.SingleEmailMessage();
            list<string> toaddress=new list<string>();
            toaddress.add(a.Supplier_Email_ID__c);
            email.setToAddresses(toaddress);
            list<string> ccaddress=new list<string>();
            ccaddress.add('kiransreeram8@gmail.com');
            email.setCcAddresses(ccaddress);
            email.setSubject('Welcome '+a.Supplier_Name__c);
            //email.setPlainTextBody('Hello supplier Welocome Onboard');
            string emailBody= messaging.renderStoredEmailTemplate(et.Id,a.id,a.Id).getHtmlBody();
            email.setHtmlBody(emailBody);
            email.setTemplateId(et.id);
            messaging.sendEmail(new messaging.SingleEmailMessage[]{email});
        }
    }
}