KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/Antra_Employee__c.object-meta.xml
<CustomObject>
    <label>Antra Employee</label>
    <nameField>
        <displayFormat>AEM-{000}</displayFormat>
        <label>Antra Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Antra Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/Employee_Mail_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Mail_Id__c</fullName>
    <label>Employee Mail Id</label>
    <type>Email</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Antra_Employee__c/fields/Mail_Unsubscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Mail_Unsubscription_Status__c</fullName>
    <defaultValue>&apos;subscribed&apos;</defaultValue>
    <inlineHelpText>true means Employee Unsubscribed</inlineHelpText>
    <label>Mail Unsubscription Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/AntraBatchprac.cls
global class AntraBatchprac implements Database.Batchable<sObject> {
    integer x=10;
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'select id,name,Employee_Mail_Id__c,First_name__c from Antra_Employee__c where Employee_Mail_Id__c !=null and Mail_Unsubscription_Status__c !=\'true\' and Date_of_Birth__c =TODAY  ';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Antra_Employee__c> empl) {
        EmailTemplate et = [select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where DeveloperName ='Birthday_Email_templete'];
        for(Antra_Employee__c emp : empl) {        
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            List<String> toAddresses = new List<String>();
            toAddresses.add(emp.Employee_Mail_Id__c);
            email.setToAddresses(toAddresses);
            List<String> ccAddresses = new List<String>();
            ccAddresses.add('kiransreeram8@live.com');
            email.setCcAddresses(ccAddresses);
            email.setSubject('Happy Birthday '+emp.First_name__c);
            string emailBody= messaging.renderStoredEmailTemplate(et.Id,emp.id,emp.Id).getHtmlBody();
            email.setHtmlBody(emailBody);
            email.setTemplateId(et.id);
            /*messaging.SingleEmailMessage[] msg =new messaging.SingleEmailMessage[]{email};
                messaging.sendEmail(msg);*/
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});
            /*list<messaging.SingleEmailMessage> msg =new list<messaging.SingleEmailMessage>();
            msg.add(email);
            messaging.sendEmail(msg);*/
            x=20;
            system.debug(x);
        }
        
    }   
    
    global void finish(Database.BatchableContext BC) {
        
    }
}