KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/Antra_Employee__c.object-meta.xml
<CustomObject>
    <label>Antra Employee</label>
    <nameField>
        <displayFormat>AEM-{000}</displayFormat>
        <label>Antra Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Antra Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/Employee_Mail_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Mail_Id__c</fullName>
    <label>Employee Mail Id</label>
    <type>Email</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/Employee_Details__c.object-meta.xml
<CustomObject>
    <label>Employee Details</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <displayFormat>DEL-{0000}</displayFormat>
    <label>Employee ID</label>
    <type>AutoNumber</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Employee_Details__c/fields/Employee_name__c.field-meta.xml
<CustomField>
    <fullName>Employee_name__c</fullName>
    <formula>text(Salution__c) + Last_name__c +&apos;  &apos;+ Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee name</label>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/AntraEmployeewebservice.cls
@RestResource(urlMapping='/kcfempprovprogram/*')
global with sharing class AntraEmployeewebservice {
@HttpGet
    global static list<Emp> getEmployeeRecord(){
        list<Emp> newemp=new list<Emp>();
        list<Employee_Details__c> emp=[SELECT Id, Name, Employee_name__c, Employee_ID__c,Email_ID__c FROM Employee_Details__c limit 10];
        for(Employee_Details__c e1:emp){
            Emp emob=new Emp();
            emob.eid=e1.Id;
            emob.empemail=e1.Email_ID__c;
            emob.empname=e1.Employee_name__c;
            emob.ename=e1.Name;
            emob.empid=e1.Employee_ID__c;
            newemp.add(emob);
        }
        return newemp;
    }
    class Emp_data{
        string name;
        string accnum;
        string site;
    }
    class Employee_Data{
        string firstname;
        string lastname;
        string email;
    }
    @HttpPost
    global static void insertEmpRecord(){
        RestRequest res=RestContext.request;
        string JsonBody=res.requestBody.tostring();
        object obj=Json.deserialize(JsonBody,Employee_Data.class);
        Employee_Data accd=(Employee_Data)obj;
        Antra_Employee__c aemp=new Antra_Employee__c();
        aemp.First_name__c=accd.firstname;
        aemp.Last_Name__c=accd.lastname;
        aemp.Employee_Mail_Id__c=accd.email;
       insert aemp; 
       
    }
    @HttpPatch
    global static void UpdateAccRecord(){
        RestRequest res=RestContext.request;
        system.debug(res);
        string JsonBody=res.requestBody.tostring();
        object obj=Json.deserialize(JsonBody,Emp_data.class);
        Emp_data accd=(Emp_data)obj;
        Account acc=new Account();
        acc.Name=accd.name;
        acc.AccountNumber=accd.accnum;
        acc.Site=accd.site;
        update acc;
    }
    @HttpDelete
    global static void deleteEmpRecord(){
        restrequest req=restcontext.request;
        system.debug(req);
        string employeeid=req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        system.debug(employeeid);
        list<Antra_Employee__c> aemp=[select id,Name from Antra_Employee__c where Name=:employeeid];
        delete aemp;
    }
}