KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/Antra_Employee__c.object-meta.xml
<CustomObject>
    <label>Antra Employee</label>
    <nameField>
        <displayFormat>AEM-{000}</displayFormat>
        <label>Antra Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Antra Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Antra_Projects__c/Antra_Projects__c.object-meta.xml
<CustomObject>
    <label>Antra Projects</label>
    <nameField>
        <label>Antra Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Antra Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Projects__c/fields/Antra_Employee__c.field-meta.xml
<CustomField>
    <fullName>Antra_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Antra Employee</label>
    <referenceTo>Antra_Employee__c</referenceTo>
    <relationshipLabel>Antra Projects</relationshipLabel>
    <relationshipName>Antra_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/ProjectUIScreenController.cls
public class ProjectUIScreenController {
    public string strselect{get;set;}
    public string projectName{get;set;}
    public string Clientname{get;set;}
    public string ProjectDuration{get;set;}
    public List<SelectOption> options {get;set;}
    public ProjectUIScreenController()
    {
        strselect = '';
        options = new List<SelectOption>();
        List<Antra_Employee__c> aemp=[SELECT id,Name,First_name__c FROM Antra_Employee__c ];
        for(Antra_Employee__c  obj : aemp)
        {
            options.add(new SelectOption(obj.Id,obj.First_name__c));
        }
    }
    public void submit(){
        Antra_Projects__c anp=new Antra_Projects__c();
        anp.Name=projectName;
        anp.Client_Name__c=Clientname;
        anp.Duration__c=ProjectDuration;
        anp.Antra_Employee__c = strselect;
        System.debug(strselect);
        /*list<Antra_Employee__c> aem=[select id,Name,First_name__c from Antra_Employee__c];
        map<id,Antra_Employee__c> projectmap=new map<id,Antra_Employee__c>();
        for(Antra_Employee__c a:aem){
            projectmap.put(a.Id,a);
            anp.Antra_Employee__c=a.Id;
        }*/
        insert anp;
    }
}