KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/Antra_Employee__c.object-meta.xml
<CustomObject>
    <label>Antra Employee</label>
    <nameField>
        <displayFormat>AEM-{000}</displayFormat>
        <label>Antra Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Antra Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Antra_Employee__c/fields/Department_ID__c.field-meta.xml
<CustomField>
    <fullName>Department_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department ID</label>
    <referenceTo>Antra_Department__c</referenceTo>
    <relationshipLabel>Antra Employees</relationshipLabel>
    <relationshipName>Antra_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/AntraEmployeeTriggerHandlerTest.cls
@istest
private class AntraEmployeeTriggerHandlerTest {
@istest
    static void method1(){
        Antra_Employee__c emp=new Antra_Employee__c();
        emp.Department_ID__c='a015j00000HnHEdAAN';
        emp.First_name__c='xyz';
        insert emp;
        Antra_Employee__c emp1=new Antra_Employee__c();
        emp1.Department_ID__c='a015j00000HnHEdAAN';
        emp1.First_name__c='xy';
        insert emp1;
        Antra_Employee__c emp2=new Antra_Employee__c();
        emp2.Department_ID__c='a015j00000HnHEdAAN';
        emp2.First_name__c='xy';
        insert emp2;
        Antra_Employee__c emp3=new Antra_Employee__c();
        emp3.Department_ID__c='a015j00000HnHEdAAN';
        emp3.First_name__c='xy';
        insert emp3;
    }
}