KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/Antra_Employee__c.object-meta.xml
<CustomObject>
    <label>Antra Employee</label>
    <nameField>
        <displayFormat>AEM-{000}</displayFormat>
        <label>Antra Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Antra Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Antra_Employee__c/fields/Department_ID__c.field-meta.xml
<CustomField>
    <fullName>Department_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department ID</label>
    <referenceTo>Antra_Department__c</referenceTo>
    <relationshipLabel>Antra Employees</relationshipLabel>
    <relationshipName>Antra_Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/Department_Name__c.field-meta.xml
<CustomField>
    <fullName>Department_Name__c</fullName>
    <formula>Department_ID__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Department Name</label>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/Employee_Mail_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Mail_Id__c</fullName>
    <label>Employee Mail Id</label>
    <type>Email</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/Employee_salary__c.field-meta.xml
<CustomField>
    <fullName>Employee_salary__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employee salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/objects/Antra_Employee__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <label>User Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/AntraEmployeeTriggerHandler.cls
public class AntraEmployeeTriggerHandler {
    Public static void useCase1(list<Antra_Employee__c > emp){
        for(Antra_Employee__c em:emp){
            integer depcount=[select count() from Antra_Employee__c where Department_ID__c=:em.Department_ID__c];
            system.debug(depcount);
            if(depcount>3){
                em.Department_ID__c.addError('cant save the record kindly choose another department');
            }
        }
    }
    public static void useCase3(list<Antra_Employee__c > emp){
        for(Antra_Employee__c em:emp){
            if(!(em.Employee_Mail_Id__c==em.User_Name__c)){
                em.User_Name__c.adderror('username should be employee mail ID');
            }
        }
    }
    public static void useCase2(list<Antra_Employee__c > emp){
        for(Antra_Employee__c em:emp){
            if((em.Department_Name__c=='SalesForce developer' ||em.Department_Name__c=='JAVA developer' ) && (em.Employee_salary__c<25000 || em.Employee_salary__c>70000)){
                em.Employee_salary__c.adderror('Developer salary should be in the range of 25k to 70k');
            }
            if((em.Department_Name__c=='Human Resource' ) && (em.Employee_salary__c<15000 || em.Employee_salary__c>25000)){
                em.Employee_salary__c.adderror('Human Resource salary should be in the range of 15k to 25k');
            }
        }
    }
}