KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/Antra_Employee__c.object-meta.xml
<CustomObject>
    <label>Antra Employee</label>
    <nameField>
        <displayFormat>AEM-{000}</displayFormat>
        <label>Antra Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Antra Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Antra_Employee__c/fields/Employee_Mobile_number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Mobile_number__c</fullName>
    <label>Employee Mobile number</label>
    <type>Phone</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/AntraEmpProviderIntegrationProg.cls
@restresource(urlMapping='/kcfEmpIntiPro/*')
global class AntraEmpProviderIntegrationProg {
    class Employee_Data{
        string empid;
        string name;
        string phone;
    }
@httppatch
    global static void EmpUpdatePro(){
        restrequest res=restcontext.request;
        string jsonbody=res.requestBody.tostring();
        system.debug(jsonbody);
        string employeeid=res.requestURI.substring(res.requestURI.lastindexof('/')+1);
        system.debug(employeeid);
        list<Antra_Employee__c> aemp=[select id,Name from Antra_Employee__c where Name =: employeeid];
        system.debug(aemp);
        object obj = json.deserialize(jsonbody, Employee_Data.class);
        Employee_Data classdata=(Employee_Data)obj;
        for(Antra_Employee__c a:aemp){
           a.First_name__c=classdata.name;
           a.Employee_Mobile_number__c=classdata.phone;
            update a;
        }
    }
}