KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/Antra_Employee__c.object-meta.xml
<CustomObject>
    <label>Antra Employee</label>
    <nameField>
        <displayFormat>AEM-{000}</displayFormat>
        <label>Antra Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Antra Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

KsheerabdhiOrgSetup/force-app/main/default/objects/Antra_Employee__c/fields/Employee_Mobile_number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Mobile_number__c</fullName>
    <label>Employee Mobile number</label>
    <type>Phone</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <label>First name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/manifest/SimbaUniversity/force-app/main/default/objects/Antra_Employee__c/fields/Street_1_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_1_Address__c</fullName>
    <label>Street 1 Address:</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

KsheerabdhiOrgSetup/force-app/main/default/classes/AntraEmployeeHandler.cls
public class AntraEmployeeHandler {
    public string efname{get;set;}
    public string elname{get;set;}
    public string embno{get;set;}
    public string eadd{get;set;}
    
    public void insertRec(){
        Antra_Employee__c aem=new Antra_Employee__c();
        aem.First_name__c=efname;
        aem.Last_Name__c=elname;
        aem.Employee_Mobile_number__c=embno;
        aem.Street_1_Address__c=eadd;
        insert aem;
    }
}